pipeline {

    agent any

    environment {
        IMAGE_NAME = "localhost:5000/fastapi-app"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('Containerization') {
                    sh """
                    docker build \
                    -t ${IMAGE_NAME}:${BUILD_NUMBER} \
                    .
                    """
                }
            }
        }

        stage('Push To Local Registry') {
            steps {
                sh """
                docker push ${IMAGE_NAME}:${BUILD_NUMBER}
                """
            }
        }

    //     stage('Deploy To Kubernetes') {
    //         steps {
    //             sh """
    //             kubectl set image deployment/fastapi-app \
    //             fastapi=${IMAGE_NAME}:${BUILD_NUMBER}

    //             kubectl rollout status deployment/fastapi-app
    //             """
    //         }
    //     }
    // }

            stage('Deploy To Kubernetes') { 
        steps { 
             sh """ 
            # Create or update Kubernetes resources
         kubectl apply -f ./k8s/

            # Update the deployment with the current build image
            kubectl set image deployment/fastapi-app \
            fastapi=${IMAGE_NAME}:${BUILD_NUMBER}

            # Wait until deployment is successful
            kubectl rollout status deployment/fastapi-app
        """ 
    } 
}

    post {
        success {
            echo 'Deployment Successful'
            sh 'kubectl get pods'
        }

        failure {
            echo 'Deployment Failed'
        }
    }
}